### ISSUE TITLE
Error al compilar en 4.9.0-8-amd64 (4.9.130-2)

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/elantech-marble-dkms#3]
```
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
Se instalarán los siguientes paquetes NUEVOS:
  elantech-marble-dkms
0 actualizados, 1 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
Se necesita descargar 108 kB de archivos.
Se utilizarán 577 kB de espacio de disco adicional después de esta operación.
Des:1 http://repo-huayra.conectarigualdad.gob.ar/huayra torbellino/main amd64 elantech-marble-dkms all 0.2.1 [108 kB]
Descargados 108 kB en 0s (1.797 kB/s)          
Seleccionando el paquete elantech-marble-dkms previamente no seleccionado.
(Leyendo la base de datos ... 404602 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../elantech-marble-dkms_0.2.1_all.deb ...
Desempaquetando elantech-marble-dkms (0.2.1) ...
Configurando elantech-marble-dkms (0.2.1) ...
Loading new elantech-marble-dkms-0.2.1 DKMS files...
Building for 4.9.0-8-amd64
Building initial module for 4.9.0-8-amd64
Error! Bad return status for module build on kernel: 4.9.0-8-amd64 (x86_64)
Consult /var/lib/dkms/elantech-marble-dkms/0.2.1/build/make.log for more information.

```

Log del dkms

```
DKMS make.log for elantech-marble-dkms-0.2.1 for kernel 4.9.0-8-amd64 (x86_64)
jue nov 22 10:40:51 -03 2018
make: se entra en el directorio '/usr/src/linux-headers-4.9.0-8-amd64'
  LD      /var/lib/dkms/elantech-marble-dkms/0.2.1/build/built-in.o
  CC [M]  /var/lib/dkms/elantech-marble-dkms/0.2.1/build/appletouch.o
  CC [M]  /var/lib/dkms/elantech-marble-dkms/0.2.1/build/bcm5974.o
/var/lib/dkms/elantech-marble-dkms/0.2.1/build/bcm5974.c: In function ‘report_tp_state’:
/var/lib/dkms/elantech-marble-dkms/0.2.1/build/bcm5974.c:567:2: error: too few arguments to function ‘input_mt_assign_slots’
  input_mt_assign_slots(input, dev->slots, dev->pos, n);
  ^~~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/elantech-marble-dkms/0.2.1/build/bcm5974.c:42:0:
/usr/src/linux-headers-4.9.0-8-common/include/linux/input/mt.h:121:5: note: declared here
 int input_mt_assign_slots(struct input_dev *dev, int *slots,
     ^~~~~~~~~~~~~~~~~~~~~
/usr/src/linux-headers-4.9.0-8-common/scripts/Makefile.build:307: fallo en las instrucciones para el objetivo '/var/lib/dkms/elantech-marble-dkms/0.2.1/build/bcm5974.o'
make[3]: *** [/var/lib/dkms/elantech-marble-dkms/0.2.1/build/bcm5974.o] Error 1
make[3]: *** Se espera a que terminen otras tareas....
/usr/src/linux-headers-4.9.0-8-common/Makefile:1528: fallo en las instrucciones para el objetivo '_module_/var/lib/dkms/elantech-marble-dkms/0.2.1/build'
make[2]: *** [_module_/var/lib/dkms/elantech-marble-dkms/0.2.1/build] Error 2
Makefile:152: fallo en las instrucciones para el objetivo 'sub-make'
make[1]: *** [sub-make] Error 2
Makefile:8: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2
make: se sale del directorio '/usr/src/linux-headers-4.9.0-8-amd64'

```

**Comment by iglosiggio** [comment]
En el kernel nuevo le pasan un 0 al último parámetro (
https://github.com/torvalds/linux/blob/master/drivers/input/mouse/bcm5974.c
).

PD: ¿Valdría la pena rebasar contra un kernel más nuevo estos drivers?

Acá hay docu de qué es cada parámetro (no sé si está actualizada a lo
último):
https://www.linuxtv.org/downloads/v4l-dvb-internals/device-drivers/API-input-mt-assign-slots.html
